"""
UPGRADED: Support Routing Task Data with Realistic Customer Scenarios
"""

SUPPORT_ROUTING_EASY_DATA = [
    {
        "ticket_subject": "Refund request for order #12345",
        "ticket_description": "I received my order but it arrived damaged. The product is unusable. I would like a full refund or replacement. Order total was $89.99.",
        "customer_type": "standard",
        "sentiment": "frustrated",
        "issue_category": "billing",
        "previous_interactions": 0,
        "account_age_days": 180,
        "is_vip": False,
        "correct_department": "billing",
        "correct_priority": "high",
        "correct_response_type": "human_review",
        "correct_tone": "empathetic",
        "difficulty": "easy",
        "urgency": "high",
        "risk": "low"
    },
    {
        "ticket_subject": "Application keeps crashing on login",
        "ticket_description": "Every time I try to log in on my iPhone 12, the app crashes immediately. I have tried uninstalling and reinstalling but the problem persists. I need this fixed ASAP.",
        "customer_type": "premium",
        "sentiment": "angry",
        "issue_category": "technical",
        "previous_interactions": 2,
        "account_age_days": 365,
        "is_vip": False,
        "correct_department": "tech_support",
        "correct_priority": "urgent",
        "correct_response_type": "human_review",
        "correct_tone": "urgent",
        "difficulty": "easy",
        "urgency": "critical",
        "risk": "low"
    },
    {
        "ticket_subject": "General inquiry about features",
        "ticket_description": "Hi, I'm interested in learning more about the premium features. Can you explain what's included in the pro plan? I'm considering upgrading from the free plan.",
        "customer_type": "free",
        "sentiment": "neutral",
        "issue_category": "general",
        "previous_interactions": 0,
        "account_age_days": 30,
        "is_vip": False,
        "correct_department": "general_support",
        "correct_priority": "medium",
        "correct_response_type": "auto_reply",
        "correct_tone": "formal",
        "difficulty": "easy",
        "urgency": "low",
        "risk": "low"
    },
]

SUPPORT_ROUTING_MEDIUM_DATA = [
    {
        "ticket_subject": "Charged twice for subscription",
        "ticket_description": "I was charged $19.99 twice this month. I only have one subscription. Please investigate and refund the duplicate charge immediately. This is unacceptable.",
        "customer_type": "premium",
        "sentiment": "angry",
        "issue_category": "billing",
        "previous_interactions": 5,
        "account_age_days": 730,
        "is_vip": True,
        "correct_department": "billing",
        "correct_priority": "urgent",
        "correct_response_type": "escalate",
        "correct_tone": "empathetic",
        "difficulty": "medium",
        "urgency": "critical",
        "risk": "medium"
    },
    {
        "ticket_subject": "Password reset not working",
        "ticket_description": "I clicked the password reset link but nothing happens. I can't access my account. I have important data there that I need to access today.",
        "customer_type": "standard",
        "sentiment": "frustrated",
        "issue_category": "technical",
        "previous_interactions": 1,
        "account_age_days": 90,
        "is_vip": False,
        "correct_department": "tech_support",
        "correct_priority": "high",
        "correct_response_type": "human_review",
        "correct_tone": "empathetic",
        "difficulty": "medium",
        "urgency": "high",
        "risk": "medium"
    },
    {
        "ticket_subject": "Wrong item received - need immediate solution",
        "ticket_description": "I ordered a blue laptop case but received a red one instead. I need the correct item by tomorrow for an important event. Can you expedite shipping or is there another solution?",
        "customer_type": "premium",
        "sentiment": "neutral",
        "issue_category": "billing",
        "previous_interactions": 3,
        "account_age_days": 200,
        "is_vip": False,
        "correct_department": "billing",
        "correct_priority": "high",
        "correct_response_type": "human_review",
        "correct_tone": "formal",
        "difficulty": "medium",
        "urgency": "high",
        "risk": "medium"
    },
]

SUPPORT_ROUTING_HARD_DATA = [
    {
        "ticket_subject": "Security concern: Unauthorized access detected",
        "ticket_description": "I noticed login attempts from unknown locations. Someone may have accessed my account without permission. I'm a VIP customer and need immediate assistance. This is urgent.",
        "customer_type": "premium",
        "sentiment": "angry",
        "issue_category": "technical",
        "previous_interactions": 10,
        "account_age_days": 1000,
        "is_vip": True,
        "correct_department": "tech_support",
        "correct_priority": "urgent",
        "correct_response_type": "escalate",
        "correct_tone": "urgent",
        "difficulty": "hard",
        "urgency": "critical",
        "risk": "critical",
        "note": "VIP + Security + Multiple previous contacts = Escalate immediately"
    },
    {
        "ticket_subject": "Billing discrepancy and service issue combined",
        "ticket_description": "My bill shows charges I don't recognize, AND the service has been glitchy. I've tried contacting support twice but got no response. I'm extremely frustrated and considering cancellation.",
        "customer_type": "premium",
        "sentiment": "angry",
        "issue_category": "mixed",
        "previous_interactions": 8,
        "account_age_days": 500,
        "is_vip": False,
        "correct_department": "escalation",
        "correct_priority": "urgent",
        "correct_response_type": "escalate",
        "correct_tone": "empathetic",
        "difficulty": "hard",
        "urgency": "critical",
        "risk": "critical",
        "note": "Multiple issues + multiple contacts + high frustration = Needs escalation"
    },
    {
        "ticket_subject": "Enterprise account setup assistance needed",
        "ticket_description": "We are interested in your enterprise plan for our organization of 500+ employees. We need help with setup, integration with our existing systems, and custom configurations.",
        "customer_type": "standard",
        "sentiment": "neutral",
        "issue_category": "general",
        "previous_interactions": 0,
        "account_age_days": 1,
        "is_vip": False,
        "correct_department": "escalation",
        "correct_priority": "high",
        "correct_response_type": "escalate",
        "correct_tone": "formal",
        "difficulty": "hard",
        "urgency": "high",
        "risk": "critical",
        "note": "Enterprise deal = Route to sales/escalation team"
    },
    {
        "ticket_subject": "API integration troubleshooting",
        "ticket_description": "Our webhook isn't receiving events even though we've configured it according to docs. We've tried debugging but can't figure it out. It's affecting our production system.",
        "customer_type": "premium",
        "sentiment": "frustrated",
        "issue_category": "technical",
        "previous_interactions": 4,
        "account_age_days": 365,
        "is_vip": False,
        "correct_department": "tech_support",
        "correct_priority": "urgent",
        "correct_response_type": "human_review",
        "correct_tone": "formal",
        "difficulty": "hard",
        "urgency": "critical",
        "risk": "critical",
        "note": "Production issue + technical complexity = Immediate human review"
    },
]
